backend:
  name: git-gateway
  branch: main

media_folder: public/uploads
public_folder: /uploads

display_url: https://rhcs.netlify.app/
logo_url: /logo.png

collections:
  - name: "tree-tours" 
    label: "Tree Tours"
    folder: "src/content/events" 
    create: true 
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - label: "Start Date and Time"
        name: "startDateTime"
        widget: "datetime"
        date_format: "YYYY-MM-DD"
        time_format: "hh:mm A"
        format: "YYYY-MM-DD hh:mm A"
        hint: "Time is in Coquitlam, BC"
      - label: "End Date and Time"
        name: "endDateTime"
        widget: "datetime"
        date_format: "YYYY-MM-DD"
        time_format: "hh:mm A"
        format: "YYYY-MM-DD hh:mm A"
        hint: "The date and time the event will finish."
      - label: "Location"
        name: "location"
        widget: "string"
        default: "Henry Esson Young Building (HEY Building)"
        required: false
        hint: "For standard Tree Tours, leave this as the default. Change it only for special events at a different location."
      - label: "Timezone"
        name: "timezone"
        widget: "hidden"
        default: "America/Vancouver"
      - { label: "Description", name: "description", widget: "markdown", modes: ['raw'], required: false }